# -*- coding: utf-8 -*-
"""single_variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/112CPUq8nN19zXXz6_TmzF1ZTdj2JQoXT
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

from google.colab import drive

df=pd.read_csv('/content/homeprices.csv')

df

new_df = df.drop('price',axis='columns')
new_df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df.area,df.price,color="red",marker='+')
plt.xlabel("square feet")
plt.ylabel("pricing")

reg=linear_model.LinearRegression()
reg.fit(new_df,df.price)

reg.predict([[3300]])

reg.coef_

reg.intercept_

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df.area,df.price,color="red",marker='+')
plt.xlabel("square feet")
plt.ylabel("pricing")
plt.plot(df.area,reg.predict(df[['area']]),color='blue')



ya=135.78767123*3300 + 180616.43835616432
ya

reg=linear_model.LinearRegression()
reg.fit(new_df,df.price)

reg.predict([[5000]])

reg.coef_

reg.intercept_

ya2=135.78767123*5000 + 180616.43835616432
ya2

d=pd.read_csv('/content/areas.csv')

d['prices']=reg.predict(d)

d

d.to_csv("prediction.csv")